# Generated by Django 5.0.3 on 2024-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='adoption_notice',
        ),
        migrations.AddField(
            model_name='adoptionnotice',
            name='animals',
            field=models.ManyToManyField(to='fellchensammlung.animal'),
        ),
    ]
