# Generated by Django 5.0.6 on 2024-08-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField(verbose_name="Inhalt")),
                ("read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer*in",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentNotification",
            fields=[
                (
                    "basenotification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fellchensammlung.basenotification",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fellchensammlung.comment",
                        verbose_name="Antwort",
                    ),
                ),
            ],
            bases=("fellchensammlung.basenotification",),
        ),
    ]
