# Generated by Django 5.0.3 on 2024-04-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarkdownContent",
            new_name="Text",
        ),
    ]
