# Generated by Django 5.0.3 on 2024-04-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0002_rename_markdowncontent_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="text",
            options={"verbose_name_plural": "Text"},
        ),
    ]
