# Generated by Django 5.0.3 on 2024-03-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0002_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
    ]
