# Generated by Django 5.0.6 on 2024-08-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0003_subscriptions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adoptionnotice",
            old_name="created_by",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="subscriptions",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="animal",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
