# Generated by Django 5.0.6 on 2024-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0003_remove_report_adoption_notice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reported_broken_rules",
            field=models.ManyToManyField(to="fellchensammlung.rule"),
        ),
    ]
