# Generated by Django 5.0.6 on 2024-06-05 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0004_alter_report_reported_broken_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "text_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fellchensammlung.text",
                    ),
                ),
                ("logged_in_only", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publish_start_time",
                    models.DateTimeField(verbose_name="Veröffentlichungszeitpunk"),
                ),
                (
                    "publish_end_time",
                    models.DateTimeField(verbose_name="Veröffentlichungsende"),
                ),
            ],
            bases=("fellchensammlung.text",),
        ),
    ]
