# Generated by Django 5.0.3 on 2024-04-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0004_alter_text_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="content",
            field=models.TextField(verbose_name="Inhalt"),
        ),
        migrations.AlterField(
            model_name="text",
            name="language",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="fellchensammlung.language",
                verbose_name="Sprache",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="text_code",
            field=models.CharField(blank=True, max_length=24, verbose_name="Text code"),
        ),
    ]
