# Generated by Django 5.0.3 on 2024-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0004_image_adoptionnotice_photos_animal_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('M_N', 'male_neutered'), ('M', 'male'), ('F_N', 'female_neutered'), ('F', 'female')], default='female', max_length=20),
            preserve_default=False,
        ),
    ]
