# Generated by Django 5.1.1 on 2024-09-30 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0005_rescueorganization_allows_using_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionnotice',
            name='last_checked',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Zuletzt überprüft am'),
        ),
    ]
