# Generated by Django 5.0.3 on 2024-04-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0005_alter_text_content_alter_text_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fellchensammlung.language",
                verbose_name="Sprache",
            ),
        ),
    ]
