# Generated by Django 5.0.3 on 2024-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0005_report_moderationaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('user_banned', 'User was banned'), ('content_deleted', 'Content was deleted'), ('comment', 'Comment was added'), ('other_action_taken', 'Other action was taken'), ('no_action_taken', 'No action was taken')], max_length=30),
        ),
    ]
