# Generated by Django 5.0.6 on 2024-06-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0005_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="type",
            field=models.CharField(
                choices=[
                    ("important", "important"),
                    ("warning", "warning"),
                    ("info", "info"),
                ],
                default="info",
                max_length=100,
            ),
        ),
    ]
