# Generated by Django 5.0.3 on 2024-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0006_alter_moderationaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='private_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='public_comment',
            field=models.TextField(blank=True),
        ),
    ]
