# Generated by Django 5.1.1 on 2024-09-30 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0006_adoptionnotice_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionnotice',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Zuletzt überprüft am'),
        ),
    ]
