# Generated by Django 5.0.6 on 2024-06-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0006_announcement_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.RemoveField(
            model_name="location",
            name="postcode",
        ),
        migrations.AddField(
            model_name="adoptionnotice",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fellchensammlung.location",
            ),
        ),
        migrations.AddField(
            model_name="adoptionnotice",
            name="location_string",
            field=models.CharField(
                default="72072", max_length=200, verbose_name="Ortsangabe"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(default=47),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="osm_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="place_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rescueorganization",
            name="location_string",
            field=models.CharField(
                default="72072", max_length=200, verbose_name="Ort der Organisation"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=2000),
        ),
    ]
