# Generated by Django 5.1.1 on 2024-10-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0007_alter_adoptionnotice_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionnoticestatus',
            name='minor_status',
            field=models.CharField(choices=[('searching', 'searching'), ('interested', 'interested'), ('waiting_for_review', 'waiting_for_review'), ('needs_additional_info', 'needs_additional_info'), ('successful_with_notfellchen', 'successful_with_notfellchen'), ('successful_without_notfellchen', 'successful_without_notfellchen'), ('animal_died', 'animal_died'), ('closed_for_other_adoption_notice', 'closed_for_other_adoption_notice'), ('not_open_for_adoption_anymore', 'not_open_for_adoption_anymore'), ('other', 'other'), ('against_the_rules', 'against_the_rules'), ('missing_information', 'missing_information'), ('technical_error', 'technical_error'), ('unchecked', 'unchecked')], max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_start_time',
            field=models.DateTimeField(verbose_name='Veröffentlichungszeitpunkt'),
        ),
    ]
