# Generated by Django 5.0.6 on 2024-06-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fellchensammlung",
            "0007_remove_location_country_remove_location_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="osm_id",
        ),
    ]
