# Generated by Django 5.0.6 on 2024-06-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0008_remove_location_osm_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="title",
        ),
    ]
