# Generated by Django 5.0.6 on 2024-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0009_remove_image_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("in_review", "in review"),
                            ("closed", "closed"),
                            ("disabled", "disabled"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "minor_status",
                    models.CharField(
                        choices=[
                            ("searching", "searching"),
                            ("interested", "interested"),
                            ("waiting_for_review", "waiting_for_review"),
                            (
                                "successful_with_notfellchen",
                                "successful_with_notfellchen",
                            ),
                            (
                                "successful_without_notfellchen",
                                "successful_without_notfellchen",
                            ),
                            ("animal_died", "animal_died"),
                            (
                                "closed_for_other_adoption_notice",
                                "closed_for_other_adoption_notice",
                            ),
                            (
                                "not_open_for_adoption_anymore",
                                "not_open_for_adoption_anymore",
                            ),
                            ("other", "other"),
                            ("against_the_rules", "against_the_rules"),
                            ("missing_information", "missing_information"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
