# Generated by Django 5.1.1 on 2024-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Schlüssel')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel')),
                ('data', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
