# Generated by Django 5.0.6 on 2024-06-06 14:51

import django.db.models.deletion
from django.db import migrations, models

from fellchensammlung.models import Status

default_status = Status.objects.create(major_status=Status.ACTIVE, minor_status="searching")


class Migration(migrations.Migration):
    dependencies = [
        ("fellchensammlung", "0010_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionnotice",
            name="status",
            field=models.ForeignKey(
                default=default_status.pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="fellchensammlung.status",
            ),
            preserve_default=False,
        ),
    ]
