# Generated by Django 5.1.1 on 2024-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0013_alter_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
