# Generated by Django 5.1.1 on 2024-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0015_rescueorganization_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefonnummer'),
        ),
    ]
