# Generated by Django 5.1.1 on 2024-11-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0016_rescueorganization_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fellchensammlung.rescueorganization', verbose_name='Organisation'),
        ),
    ]
