# Generated by Django 5.1.1 on 2024-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0017_user_organization_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
