# Generated by Django 5.1.1 on 2024-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0019_rename_comment_rescueorganization_internal_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueorganization',
            name='internal_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Interner Kommentar'),
        ),
    ]
