# Generated by Django 5.1.1 on 2024-11-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0022_alter_user_reason_for_signup_alter_user_trust_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigung per E-Mail'),
        ),
    ]
