# Generated by Django 5.1.4 on 2024-12-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0029_rename_andoptionnoticenotification_adoptionnoticenotification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchsubscription',
            old_name='radius',
            new_name='max_distance',
        ),
    ]
