# Generated by Django 5.1.4 on 2024-12-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0030_rename_radius_searchsubscription_max_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchsubscription',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fellchensammlung.location'),
        ),
        migrations.AlterField(
            model_name='searchsubscription',
            name='max_distance',
            field=models.IntegerField(choices=[(20, '20 km'), (50, '50 km'), (100, '100 km'), (200, '200 km'), (500, '500 km')], null=True),
        ),
    ]
