# Generated by Django 5.1.4 on 2025-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0032_searchsubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='external_object_identifier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='External Object Identifier'),
        ),
        migrations.AddField(
            model_name='rescueorganization',
            name='external_source_identifier',
            field=models.CharField(blank=True, choices=[('OSM', 'Open Street Map')], max_length=200, null=True, verbose_name='External Source Identifier'),
        ),
    ]
