# Generated by Django 5.1.4 on 2025-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0034_speciesspecificurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.TextField(max_length=2000, verbose_name='Alternativtext'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_broken_rules',
            field=models.ManyToManyField(to='fellchensammlung.rule', verbose_name='Regeln gegen die verstoßen wurde'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_comment',
            field=models.TextField(blank=True, verbose_name='Kommentar/Zusätzliche Information'),
        ),
    ]
