# Generated by Django 5.1.4 on 2025-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0035_alter_image_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelesen am'),
        ),
    ]
