# Generated by Django 5.1.4 on 2025-03-09 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0037_alter_basenotification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum der letzten Prüfung'),
            preserve_default=False,
        ),
    ]
