# Generated by Django 5.1.4 on 2025-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0038_rescueorganization_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueorganization',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum der letzten Prüfung'),
        ),
    ]
