# Generated by Django 5.1.4 on 2025-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0039_alter_rescueorganization_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueorganization',
            name='allows_using_materials',
            field=models.CharField(choices=[('allowed', 'Usage allowed'), ('requested', 'Usage requested'), ('denied', 'Usage denied'), ('other', "It's complicated"), ('not_asked', 'Not asked')], default='not_asked', max_length=200, verbose_name='Erlaubt Nutzung von Inhalten'),
        ),
    ]
