# Generated by Django 5.1.4 on 2025-04-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0042_location_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='countrycode',
        ),
    ]
