# Generated by Django 5.1.4 on 2025-04-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0043_rename_country_location_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=200),
        ),
    ]
