# Generated by Django 5.1.4 on 2025-04-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0045_importantlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantlocation',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fellchensammlung.location'),
        ),
    ]
