# Generated by Django 5.2.1 on 2025-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0046_alter_importantlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionnotice',
            name='further_information',
            field=models.URLField(blank=True, help_text='Verlinke hier die Quelle der Vermittlung (z.B. die Website des Tierheims', null=True, verbose_name='Link zu mehr Informationen'),
        ),
        migrations.AlterField(
            model_name='adoptionnotice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Titel der Vermittlung'),
        ),
        migrations.AlterField(
            model_name='rescueorganization',
            name='location_string',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ort der Organisation'),
        ),
    ]
