# Generated by Django 5.2.1 on 2025-06-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0048_alter_adoptionnotice_further_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='exclude_from_check',
            field=models.BooleanField(default=False, help_text='Organisation von der manuellen Überprüfung ausschließen, z.B. weil Tiere nicht online geführt werden', verbose_name='Von Prüfung ausschließen'),
        ),
    ]
