# Generated by Django 5.2.1 on 2025-07-13 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0054_alter_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='ongoing_communication',
            field=models.BooleanField(default=False, help_text='Es findet gerade Kommunikation zwischen Notfellchen und der Organisation statt.', verbose_name='In aktiver Kommunikation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_to_notify',
            field=models.ForeignKey(help_text='Useraccount der Benachrichtigt wird', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger*in'),
        ),
    ]
