# Generated by Django 5.2.1 on 2025-07-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0055_rescueorganization_ongoing_communication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescueorganization',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='rescueorganization',
            name='specializations',
            field=models.ManyToManyField(to='fellchensammlung.species'),
        ),
    ]
