# Generated by Django 5.2.1 on 2025-07-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0056_alter_rescueorganization_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeciesSpecialization',
        ),
    ]
