# Generated by Django 5.2.1 on 2025-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0058_socialmediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='twenty_id',
            field=models.UUIDField(blank=True, help_text='ID der der Organisation in Twenty', null=True, verbose_name='Twenty-ID'),
        ),
        migrations.AlterField(
            model_name='rescueorganization',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='fellchensammlung.species'),
        ),
    ]
