# Generated by Django 5.2.1 on 2025-08-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0059_rescueorganization_twenty_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionnotice',
            options={'permissions': [('create_active_adoption_notice', 'Can create an active adoption notice')], 'verbose_name': 'Vermittlung', 'verbose_name_plural': 'Vermittlungen'},
        ),
        migrations.AlterModelOptions(
            name='adoptionnoticestatus',
            options={'verbose_name': 'Vermittlungsstatus', 'verbose_name_plural': 'Vermittlungsstati'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Tier', 'verbose_name_plural': 'Tiere'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterModelOptions(
            name='importantlocation',
            options={'verbose_name': 'Wichtiger Standort', 'verbose_name_plural': 'Wichtige Standorte'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Standort', 'verbose_name_plural': 'Standorte'},
        ),
        migrations.AlterModelOptions(
            name='moderationaction',
            options={'verbose_name': 'Moderationsaktion', 'verbose_name_plural': 'Moderationsaktionen'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Benachrichtigung', 'verbose_name_plural': 'Benachrichtigungen'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Meldung', 'verbose_name_plural': 'Meldungen'},
        ),
        migrations.AlterModelOptions(
            name='rescueorganization',
            options={'ordering': ['name'], 'verbose_name': 'Tierschutzorganisation', 'verbose_name_plural': 'Tierschutzorganisationen'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Regel', 'verbose_name_plural': 'Regeln'},
        ),
        migrations.AlterModelOptions(
            name='searchsubscription',
            options={'verbose_name': 'Abonnierte Suche', 'verbose_name_plural': 'Abonnierte Suchen'},
        ),
        migrations.AlterModelOptions(
            name='speciesspecificurl',
            options={'verbose_name': 'Tierartspezifische URL', 'verbose_name_plural': 'Tierartspezifische URLs'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.AlterModelOptions(
            name='timestamp',
            options={'verbose_name': 'Zeitstempel', 'verbose_name_plural': 'Zeitstempel'},
        ),
        migrations.AddField(
            model_name='adoptionnotice',
            name='adoption_notice_status',
            field=models.TextField(choices=[('active_searching', 'Searching'), ('active_interested', 'Interested'), ('awaiting_action_waiting_for_review', 'Waiting for review'), ('awaiting_action_needs_additional_info', 'Needs additional info'), ('closed_successful_with_notfellchen', 'Successful (with Notfellchen)'), ('closed_successful_without_notfellchen', 'Successful (without Notfellchen)'), ('closed_animal_died', 'Animal died'), ('closed_for_other_adoption_notice', 'Closed for other adoption notice'), ('closed_not_open_for_adoption_anymore', 'Not open for adoption anymore'), ('closed_other', 'Other (closed)'), ('disabled_against_the_rules', 'Against the rules'), ('disabled_unchecked', 'Unchecked'), ('disabled_other', 'Other (disabled)')], default='disabled_other', max_length=64, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
