# Generated by Django 5.2.1 on 2025-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0062_alter_adoptionnotice_adoption_notice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionnotice',
            name='adoption_process',
            field=models.TextField(blank=True, choices=[('contact_person_in_an', 'Kontaktiere die Person im Vermittlungstext')], max_length=64, null=True, verbose_name='Adoptionsprozess'),
        ),
    ]
