# Generated by Django 5.2.1 on 2025-09-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0063_adoptionnotice_adoption_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photos',
            field=models.ManyToManyField(blank=True, to='fellchensammlung.image', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('F', 'Weiblich'), ('M', 'Männlich'), ('M_N', 'Männlich, kastriert'), ('F_N', 'Weiblich, kastriert'), ('I', 'Intergeschlechtlich')], max_length=20, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='adoption_notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fellchensammlung.adoptionnotice', verbose_name='Vermittlung'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.TextField(help_text='Beschreibe das Bild für blinde und sehbehinderte Menschen', max_length=2000, verbose_name='Alternativtext'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Landkreis'),
        ),
        migrations.AlterField(
            model_name='location',
            name='housenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_to_notify',
            field=models.ForeignKey(help_text='Useraccount der benachrichtigt wird', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger*in'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert am'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fellchensammlung.language', verbose_name='Sprache'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_identifier',
            field=models.CharField(help_text='Ein eindeutiger Identifikator der Regel. Ein Regelobjekt derselben Regel in einer anderen Sprache muss den gleichen Identifikator haben', max_length=24, verbose_name='Regel-ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_text',
            field=models.TextField(verbose_name='Regeltext'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert am'),
        ),
        migrations.AlterField(
            model_name='searchsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='searchsubscription',
            name='sex',
            field=models.CharField(choices=[('F', 'Weiblich'), ('M', 'Männlich'), ('M_N', 'Männlich, kastriert'), ('F_N', 'Weiblich Kastriert'), ('I', 'Intergeschlechtlich'), ('A', 'Alle')], max_length=20, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='searchsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert am'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='adoption_notice',
            field=models.ForeignKey(help_text='Vermittlung die abonniert wurde', on_delete=django.db.models.deletion.CASCADE, to='fellchensammlung.adoptionnotice', verbose_name='Vermittlung'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
    ]
