# Generated by Django 5.2.1 on 2025-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0064_alter_animal_name_alter_animal_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
    ]
