# Generated by Django 5.2.1 on 2025-09-06 13:05

from django.db import migrations


def migrate_slug(apps, schema_editor):
    Species = apps.get_model("fellchensammlung", "Species")
    for species in Species.objects.all():
        species.slug = f"species-{species.id}"
        species.save()


class Migration(migrations.Migration):
    dependencies = [
        ('fellchensammlung', '0065_species_slug'),
    ]

    operations = [
        migrations.RunPython(migrate_slug),
    ]
