# Generated by Django 5.2.1 on 2025-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0066_add_slug_to_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
