# Generated by Django 5.2.8 on 2025-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellchensammlung', '0069_rescueorganization_regular_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mod_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Moderationsnotizen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reason_for_signup',
            field=models.TextField(help_text="Wir würden gerne wissen warum du dich registrierst, ob du dich z.B. Tiere eines bestimmten Tierheim einstellen willst 'nur mal gucken' willst. Beides ist toll! Wenn du für ein Tierheim/eine Pflegestelle arbeitest kontaktieren wir dich ggf. um dir erweiterte Rechte zu geben.", verbose_name='Grund für die Registrierung'),
        ),
    ]
