# Generated by Django 5.2.8 on 2026-01-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0073_adoption_notice_status_successful"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Geburtsdatum"),
        ),
        migrations.AlterField(
            model_name="historicalanimal",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Geburtsdatum"),
        ),
        migrations.AlterField(
            model_name="historicalrescueorganization",
            name="external_object_identifier",
            field=models.CharField(
                blank=True,
                help_text="Id des Objekts in der externen Datenbank (kann leer gelassen werden)",
                max_length=200,
                null=True,
                verbose_name="External Object Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrescueorganization",
            name="external_source_identifier",
            field=models.CharField(
                blank=True,
                choices=[("OSM", "Open Street Map")],
                help_text="Name der Datenbank aus der die Tierschutzorganisation importiert wurde (kann leer gelassen werden)",
                max_length=200,
                null=True,
                verbose_name="External Source Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrescueorganization",
            name="parent_org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fellchensammlung.rescueorganization",
                verbose_name="Übergeordnete Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="rescueorganization",
            name="external_object_identifier",
            field=models.CharField(
                blank=True,
                help_text="Id des Objekts in der externen Datenbank (kann leer gelassen werden)",
                max_length=200,
                null=True,
                verbose_name="External Object Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="rescueorganization",
            name="external_source_identifier",
            field=models.CharField(
                blank=True,
                choices=[("OSM", "Open Street Map")],
                help_text="Name der Datenbank aus der die Tierschutzorganisation importiert wurde (kann leer gelassen werden)",
                max_length=200,
                null=True,
                verbose_name="External Source Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="rescueorganization",
            name="parent_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fellchensammlung.rescueorganization",
                verbose_name="Übergeordnete Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="speciesspecificurl",
            name="rescue_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species_specific_urls",
                to="fellchensammlung.rescueorganization",
                verbose_name="Tierschutzorganisation",
            ),
        ),
    ]
