# Generated by Django 5.2.8 on 2026-02-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fellchensammlung", "0074_alter_animal_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionnotice",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="historicaladoptionnotice",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalrescueorganization",
            name="allows_using_materials",
            field=models.CharField(
                choices=[
                    ("allowed", "Nutzung erlaubt"),
                    ("requested", "Nutzung angefragt"),
                    ("denied", "Nutzung verweigert"),
                    ("other", "Es ist kompliziert"),
                    ("not_asked", "Nutzung noch nicht angefragt"),
                ],
                default="not_asked",
                max_length=200,
                verbose_name="Erlaubt Nutzung von Inhalten",
            ),
        ),
        migrations.AlterField(
            model_name="rescueorganization",
            name="allows_using_materials",
            field=models.CharField(
                choices=[
                    ("allowed", "Nutzung erlaubt"),
                    ("requested", "Nutzung angefragt"),
                    ("denied", "Nutzung verweigert"),
                    ("other", "Es ist kompliziert"),
                    ("not_asked", "Nutzung noch nicht angefragt"),
                ],
                default="not_asked",
                max_length=200,
                verbose_name="Erlaubt Nutzung von Inhalten",
            ),
        ),
    ]
