# Generated by Django 5.2.8 on 2026-02-07 21:32
import uuid

from django.db import migrations
from django.utils.text import slugify


def add_slug(Obj):
    for an in Obj.objects.all():
        slug = slugify(an.name)
        if not Obj.objects.filter(slug=slug).exists():
            an.slug = slug
            an.save()
        else:
            an.slug = slug + str(uuid.uuid4())
            an.save()


def migrate_slug(apps, schema_editor):
    AdoptionNotice = apps.get_model("fellchensammlung", "AdoptionNotice")
    add_slug(AdoptionNotice)
    HistoricalAdoptionNotice = apps.get_model("fellchensammlung", "HistoricalAdoptionNotice")
    add_slug(HistoricalAdoptionNotice)


class Migration(migrations.Migration):
    dependencies = [
        (
            "fellchensammlung",
            "0075_adoptionnotice_slug_historicaladoptionnotice_slug_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_slug),
    ]
