# Generated by Django 5.2.8 on 2026-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellchensammlung", "0076_migrate_an_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoptionnotice",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="historicaladoptionnotice",
            name="slug",
            field=models.SlugField(),
        ),
    ]
